global:
  scrape_interval: 15s

  external_labels:
    monitor: "codelab-monitor"

scrape_configs:
  - job_name: "promethues"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "redis_exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]