FROM redis

COPY redis.conf /etc/redis/redis.conf

RUN chown redis:redis /etc/redis/redis.conf
RUN chown redis:redis /etc/redis/

COPY entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]